[application]
name = "kanban_planner"
default_platform = "web"

[web.app]
title = "kanban_planner"

[web.resource]

[web.resource.dev]

[web.build]
target = "web"
dist = "dist"

[web.dev]
port = 8080
open = true