[application]
name = "kanban_planner"
default_platform = "web"

[web.app]
title = "Kanban Planner"

[web.resource]
dev = {}

[web.build]
target = "web"
dist = "dist"

[web.dev]
port = 8080
open = true

[web.watcher]
watch_path = ["src", "assets"]
index_on_404 = true
