[application]
name = "kanban_planner"
default_platform = "web"

[web.app]
title = "Kanban Planner"

[web.resource]
assets = "assets"

[web.build]
target = "web"
dist = "dist"

[web.dev]
port = 8080
open = true

[web.watcher]
watch_path = ["src", "assets", "tailwind.config.js", "src/interface/tailwind.css"]

[web.tailwindcss]
input = "src/interface/tailwind.css"
config = "tailwind.config.js"